### ISSUE TITLE
[forms] allow multiple widgets on on row

### ISSUE THREAD

**Issue by sgandon** [Talend/ui#207]
as described in the UX requirements, some widgets for editing different property in a form may require to be aligned, the most relevant example is the <host><port> properties.
Today the react-form does not allow for multiple widgets to be layed-out on the same.
It would be nice to provide this feature since it is already supported by daikon properties layout and also rendered in the Studio.
In https://jira.talendforge.org/browse/TDKN-129 we also would like a way to say that those widgets are to be placed on a single row whatever is the layout vertical or horizontal, something like a desired same row and a required same row.

One quick workaround has been mentioned would be to have specific widgets for that kind of requirements. It is possible but do not leave much to to flexibility.
It would be nice to have a proper assessment of the react-form to see if it is possible or not and what is the cost.

**Comment by sgandon** [comment]
here is an example of the form definition using *addColumn* to add multiple components in a row
https://github.com/Talend/components/blob/3602fb87c620653dd11199acd584bb77a944feab/core/components-common-oauth/src/main/java/org/talend/components/common/oauth/OauthProperties.java#L47
```
Form form = Form.create(this, Form.MAIN);
        form.addRow(clientId);
        form.addColumn(clientSecret);
        form.addRow(callbackHost);
        form.addColumn(callbackPort);
```
Here 2 rows are added with 2 columns.

**Comment by frassinier** [comment]
We can easily imagine a relative positioning by introducing `ui:nextTo` but we need to be sure of the `ui:order`. It should be the same as DOM.

**Comment by jsomsanith** [comment]
No requirements for now but this is possible with the next versions of forms that is in progress.
On the current version, react-jsonSchema-form implies that the json-schema follows the ui-schema. There is no easy solution.
Let's bet on next version of forms instead of the current one.
