### ISSUE TITLE
[cmf] feat(router): add support for componentS settings

### ISSUE THREAD

**Issue by talend-glorieux** [Talend/ui#22]
_From @jmfrancois on August 12, 2016 8:17_

With react-router you can use component**S**

The main problem is to pass settings to theses components

Check route.js

_Copied from original issue: Talend/react-cmf#8_

**Comment by talend-glorieux** [comment]
_From @acateland on August 30, 2016 16:9_

When passing multiple components for one route.

**Comment by jmfrancois** [comment]
will never been done because we will switch to router v4 before
