### ISSUE TITLE
[generator] Side panel - active status

### ISSUE THREAD

**Issue by uyildizoglu** [Talend/ui#235]
In the project generated by `yo talend:react-cmf`, on side panel (menu left) the selected category is not visually highlighted. The background change is only hover. But the active category should receive a darker background (25% darker theme color).

**Comment by jmfrancois** [comment]
I guess this is only a matter of version because it has been fixed in #214

**Comment by jsomsanith** [comment]
@mtikhinskaya @sdwvit can tou update Talend/ui version in your project and check if the version upgrade fix the issue ?

**Comment by acateland** [comment]
guess we can close this issue
