### ISSUE TITLE
[cmf] add kind of connect function to wrap components

### ISSUE THREAD

**Issue by talend-glorieux** [Talend/ui#25]
_From @jmfrancois on August 11, 2016 15:12_

connect create a wrapper to let your component access to store.
But we also have i18n which need this.

This is the signal we may need other wrapper.

So should we create a function which create the needed wrapper with a simple API ?

uiWrapper(options)(MyComponent)

options should support connect, i18n and so on

_Copied from original issue: Talend/react-cmf#5_

**Comment by jmfrancois** [comment]
done with cmfConnect
