### ISSUE TITLE
App Header needs enhancements

### ISSUE THREAD

**Issue by atereshkevich** [Talend/ui#258]
On app header different dropdowns are needed, (currently there is only one possible):
    - icon + label (e.g. user menu)
    - icon + label without (e.g. app launcher)
    - dropdown menu should also allow using icons on left if needed (e.g. app launcher) 
    - icon + label + caret (e.g. environment selection) updating the label with the selected item on the dropdown

**Comment by jmfrancois** [comment]
please give enough information so I can reproduce the issue

**Comment by jmfrancois** [comment]
For sure. Please start by opening a branch to expose theses examples in the story (update existing examples).
Next try to implement it in components to see what is missing.

http://talend.surge.sh/components/?selectedKind=AppHeaderBar&selectedStory=default&full=0&down=1&left=1&panelRight=0&downPanel=kadirahq%2Fstorybook-addon-actions%2Factions-panel
