### ISSUE TITLE
[cmf] add support for i18n

### ISSUE THREAD

**Issue by talend-glorieux** [Talend/ui#26]
_From @jmfrancois on August 11, 2016 14:53_

The goal is to first discuss some point and then provide an implementation in Pull request #23 

_Copied from original issue: Talend/react-cmf#4_

**Comment by talend-glorieux** [comment]
_From @jmfrancois on September 6, 2016 14:7_

First question : should we enforce the use of i18n in a react-cmf project ?

please answer with 👍 👎

**Comment by talend-glorieux** [comment]
_From @jmfrancois on January 23, 2017 12:45_

https://www.npmjs.com/package/counterpart
https://github.com/i18next/react-i18next

**Comment by jmfrancois** [comment]
After discussion we have decided to let the choice on the project side of the technologies to use.
cmf-settings script support i18next extraction
