### ISSUE TITLE
Components do not support different locales

### ISSUE THREAD

**Issue by atereshkevich** [Talend/ui#278]
Some components have hardcoded english labels in code. For example in component "SelectSortBy.component.js" there are hardcoded values for order type: 'DESCENDING', 'ASCENDING'.
Depending on user locale component must display correct values. Locale can be added as a new property of a component.

**Comment by jsomsanith** [comment]
This is a more global topic.
We need to work on internationalization in Talend/ui and it should work for all React and Angular project.
@jmfrancois has already thought about this topic and I plan to work on that as a transversal subject

**Comment by jsomsanith** [comment]
Introduced i18n in #658
