### ISSUE TITLE
[forms] Create a list widget for filter component

### ISSUE THREAD

**Issue by talend-glorieux** [Talend/ui#31]
_From @jlamiel on December 15, 2016 13:46_

Component filter will need to handle list of complex elements.

Here is the (not up-to-date) mockup from Marc.  

![image](https://cloud.githubusercontent.com/assets/4313434/21226187/a9767900-c2d4-11e6-8e8a-1b23af5ab8ba.png)

The description of the components itself can be found here : https://jira.talendforge.org/browse/TFD-168

_Copied from original issue: Talend/react-talend-forms#55_

**Comment by jsomsanith** [comment]
In progress in an app implem, not in the ui repo
