### ISSUE TITLE
Incorrect classes for next/previous buttons on the Pagination component.

### ISSUE THREAD

**Issue by vyshkov** [Talend/ui#323]
Hi. It seems we are using **font awesome** inside our components.
Please look inside elements with classes :
```
talend-pagination-nav-to-first
talend-pagination-nav-to-prev
talend-pagination-nav-to-next
talend-pagination-nav-to-last
```
You can inspect it [here](http://306.talend.surge.sh/components/?selectedKind=List&selectedStory=Table%20%28default%29&full=0&down=1&left=1&panelRight=0&downPanel=kadirahq%2Fstorybook-addon-actions%2Factions-panel)

Please correct me if i wrong, but we should use Talend icons: 'talend-chevron-left', 'talend-chevron-end' ... etc.

**Comment by jsomsanith** [comment]
This has been done in #428
