### ISSUE TITLE
[forms] Description vs ui:help

### ISSUE THREAD

**Issue by talend-glorieux** [Talend/ui#35]
_From @jlamiel on December 7, 2016 16:35_

We need to have a title on a field, sometime parameter can be complex to understand, we might need to add some documentation or links to a field.

Related to that : Widget range doesn't show the title but show the value instead and ui:help is show as well

_Copied from original issue: Talend/react-talend-forms#45_

**Comment by jsomsanith** [comment]
Done on the next version of forms : http://talend.surge.sh/forms/?selectedKind=Core%20concepts&selectedStory=Core-simple
For example on Last name input. You have a description from uiSchema.
Let's bet on the next version of forms
