### ISSUE TITLE
[components] Autoprefixer

### ISSUE THREAD

**Issue by talend-glorieux** [Talend/ui#39]
_From @frassinier on October 19, 2016 9:50_

:warning: We must deal with `autoprefixer` task with Webpack for [this piece of code](https://github.com/Talend/react-talend-components/pull/27/files#diff-396c42a24f608454de67e558b76989daR29) for example

_Copied from original issue: Talend/react-talend-components#33_

**Comment by jsomsanith** [comment]
Done in #104
