### ISSUE TITLE
[layout] On small screens layout hides right column in TwoColumns mode

### ISSUE THREAD

**Issue by sdwvit** [Talend/ui#404]
![screenshot from 2017-04-24 17-35-59](https://cloud.githubusercontent.com/assets/8777372/25342382/94e0e92a-2914-11e7-9720-32cc094a219e.png)
![screenshot from 2017-04-24 17-36-21](https://cloud.githubusercontent.com/assets/8777372/25342381/94df3c1a-2914-11e7-9930-3f4bedaff1c8.png)

**Comment by jsomsanith** [comment]
The layout component was not designed for that. Looking at the storybook, it is for a main page with a side panel and a content that won't wrap.
In your case I think you should either don't use this component here or to add a `flex-wrap` on `.tc-layout-two-columns` classname in your app.
