### ISSUE TITLE
[containers] bug(CircularProgress): IE11 - icon not spinning

### ISSUE THREAD

**Issue by talend-glorieux** [Talend/ui#41]
_From @charlesnguyen on November 9, 2016 11:18_

![bug circularprogress](https://cloud.githubusercontent.com/assets/13314851/20136671/5f0ac2ba-a676-11e6-8b51-86ee7e9d5b9b.png)

_Copied from original issue: Talend/react-talend-components#91_

**Comment by talend-glorieux** [comment]
_From @acateland on November 9, 2016 14:39_

someone using windows should take on this ^^

**Comment by jsomsanith** [comment]
A dev has already been done. Doing the same animation is not possible du to some css properties not supported on IE.
A workaround has been implemented, we have another animation on IE
![loading](https://user-images.githubusercontent.com/10761073/27487511-3bc802a2-5834-11e7-836e-928c9a071f49.gif)
