### ISSUE TITLE
[components]The title cell will be covered by the actions when the windows become small enough

### ISSUE THREAD

**Issue by HuanLi-talend** [Talend/ui#463]
when resize the window to a small one and mouse over to the title cell,  it will be covered by actions buttons and can't be clicked.

**Comment by jsomsanith** [comment]
Switch to virtualized implementation. 
* You just have to add a props in `<List>` component
* You'll have to do some css to manage the size of each column : http://talend.surge.sh/components/?selectedKind=Virtualized%20List&selectedStory=List%20>%20Table
