### ISSUE TITLE
[forms/DataList] add placeholder

### ISSUE THREAD

**Issue by mtikhinskaya** [Talend/ui#489]
There are no possibility to add placeholder to DataList component

**Comment by talend-glorieux** [comment]
You might be able to pass a placeholder in the inputProps.
https://github.com/moroshko/react-autowhatever/blob/e9cd66f903f53d51b2fc47ac8bcac25a841f9494/demo/standalone/app.js#L35

**Comment by talend-glorieux** [comment]
I was wrong looks like those are fixed on our side. 
It would only require the addition of the placeholder to the inputProps.
https://github.com/Talend/ui/blob/master/packages/forms/src/widgets/DatalistWidget/DatalistWidget.js#L125

**Comment by talend-glorieux** [comment]
@mtikhinskaya Does it solve you issue?

**Comment by mtikhinskaya** [comment]
Yes. But placeholder appears in dropdown menu.
