### ISSUE TITLE
[Form] Buttons of 'Array' feature disappear

### ISSUE THREAD

**Issue by hbhong** [Talend/ui#681]
When open  [Talend form  storybook](http://talend.surge.sh/forms) and switch to 'Array' tab , the  buttons disappear (up,down,and delete), just 'add' button get a line .

**Comment by jmfrancois** [comment]
the issue is because the widget use glyphicons and we don't load the font
two solutions:
- load the font
- or override the widget to use our svg talend icons

**Comment by jsomsanith** [comment]
Duplicate #164
