### ISSUE TITLE
Sharing custom components

### ISSUE THREAD

**Issue by natashasweety7** [Talend/ui#819]
By following Some wrong window
i have installed one custom component (tRedirectOutput) by placing it in the following path
C:\Users\katde02\Documents\Talend\TOS_DI-20170623_1246-V6.4.1\plugins\org.talend.designer.components.localprovider_6.4.1.20170623_1246\components
 
By default this path includes all the predefined components
 
After installing custom component  all my other jobs are failing with error in all components stating 
 
Detail Message: outtFileOutputDelimited_1 cannot be resolved
There may be some other errors caused by JVM compatibility. Make sure your JVM setup is similar to the studio.      at org.[talend](https://mindmajix.com/talend-training).designer.runprocess.JobErrorsChecker.checkLastGenerationHasCompilationError(JobErrorsChecker.java:326)            at org.talend.designer.runprocess.DefaultRunProcessService.checkLastGenerationHasCompilationError(DefaultRunProcessService.java:380)
 
How can i fix this this issue
It is affect all other  jobs.

**Comment by acateland** [comment]
@natashasweety7 hello i think you post this issue on the wrong repository

**Comment by jsomsanith** [comment]
This repo is our frontend open source repository

**Comment by jsomsanith** [comment]
Erratum : on Talend Open Studio, you can ask questions in the forum : https://www.talendforge.org/forum/
