### ISSUE TITLE
CMF: Action are referenced by to many differents props

### ISSUE THREAD

**Issue by acateland** [Talend/ui#852]
On some components CMFAction are resolved by props.id, props.name, props.actionIds

One point, no standard html properties should be used for the internal working of CMF.

Second point only one props name should be used to resolve CMFActions.

Third point, we need to document each usage of props that do not respect proposal one and two.

Fourth point, i propose cmfActionId as the only props that should be used to pass CMFAction indentifier for the sake of its resolution.

Fith we need to fix this.

**Comment by jmfrancois** [comment]
actionId is already supported why change that ?
actionIds is not public but should be internal for stuff like dropdown which is a set of action so to build items as actions.

I would say CMF should never use native props. (name and id are native props)

**Comment by jmfrancois** [comment]
CMF `actions` API are deprecated
👍 we don t use any native html properties now internally in CMF
Need to cleanup containers now
