### ISSUE TITLE
[CMF] React router v4 integration

### ISSUE THREAD

**Issue by acateland** [Talend/ui#90]
React router v4 just hit beta stage and its api is set in stone
https://twitter.com/mjackson/status/826114904914489344

Since V4 is a different beast than router V2/3 we should talk on how we will itegrate it into cmf and our apps.

Here will be collected documentation about our integration plan, links to various ressource etc.

FAQ
Bundle size ?
React Router V4 is lighter than V3/2.
What about the api change ?
React Router have completely different api for route handling and declaration wich is LOT simpler and more powerfull.
V2/3 version are dropped altogether ?
No V3 will be kept and maintened for sometime.

Please contribute in following comments.

// doc entry point
https://github.com/ReactTraining/react-router/tree/v4
// migration guide incomplete
Https://gist.github.com/mjackson/33f51e9d6b9ea18b467c613fbbcf50e1
// codepen playground
https://t.co/EUZkuDfowr

**Comment by frassinier** [comment]
Please, could you produce a **TL;DR** for everyone? :D  
What's your opinion on that upgrade? Should we do it? Now?

**Comment by jsomsanith** [comment]
#324

**Comment by jmfrancois** [comment]
The PR is ready but after some thought react-router will not give us anything that we dont have already.
React-Router add an external component that trigger react rendering.
React-Router-Redux sync history  into redux

I prefer keep sync history into redux + API so we keep only the redux->react notification and source of rendering trigger.
