### ISSUE TITLE
never ever access to the application trought context.store.getState inside of a component.

### ISSUE THREAD

**Issue by acateland** [Talend/ui#925]
https://github.com/Talend/ui/blob/c692b4d8d9450294461c5d0f016fa542fdfa6aac/packages/containers/src/DeleteResource/DeleteResource.container.js#L41

this should be given trought the mapStateToProps function

doing this prevent the component to be rerendered by cmfConnect if collection resourceType is mutated

**Comment by jmfrancois** [comment]
has been fixed
